/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1.View;

import javaapplication1.Control.Controller;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Rizky
 */
public class SignUp extends javax.swing.JFrame {

    public JButton getjBtnKembali() {
        return jBtnKembali;
    }

    public void setjBtnKembali(JButton jBtnKembali) {
        this.jBtnKembali = jBtnKembali;
    }

    public JButton getjBtnSignUp() {
        return jBtnSignUpAnggota;
    }

    public void setjBtnSignUp(JButton jBtnSignUp) {
        this.jBtnSignUpAnggota = jBtnSignUp;
    }

    public JTextField getjTxtAlamatSignUp() {
        return jTxtAlamatSignUp;
    }

    public void setjTxtAlamatSignUp(JTextField jTxtAlamatSignUp) {
        this.jTxtAlamatSignUp = jTxtAlamatSignUp;
    }

    public JTextField getjTxtEmailSignUp() {
        return jTxtEmailSignUp;
    }

    public void setjTxtEmailSignUp(JTextField jTxtEmailSignUp) {
        this.jTxtEmailSignUp = jTxtEmailSignUp;
    }

    public JTextField getjTxtNamaSignUp() {
        return jTxtNamaSignUp;
    }

    public void setjTxtNamaSignUp(JTextField jTxtNamaSignUp) {
        this.jTxtNamaSignUp = jTxtNamaSignUp;
    }

    public JTextField getjTxtPasswordSignUp() {
        return jTxtPasswordSignUp;
    }

    public void setjTxtPasswordSignUp(JTextField jTxtPasswordSignUp) {
        this.jTxtPasswordSignUp = jTxtPasswordSignUp;
    }

    public JTextField getjTxtUsernameSignUp() {
        return jTxtUsernameSignUp;
    }

    public void setjTxtUsernameSignUp(JTextField jTxtUsernameSignUp) {
        this.jTxtUsernameSignUp = jTxtUsernameSignUp;
    }

    public JButton getjBtnSignUpAnggota() {
        return jBtnSignUpAnggota;
    }

    public void setjBtnSignUpAnggota(JButton jBtnSignUpAnggota) {
        this.jBtnSignUpAnggota = jBtnSignUpAnggota;
    }

    public JButton getjBtnSignUpPetugas() {
        return jBtnSignUpPetugas;
    }

    public void setjBtnSignUpPetugas(JButton jBtnSignUpPetugas) {
        this.jBtnSignUpPetugas = jBtnSignUpPetugas;
    }

    public JTextField getjTxtId() {
        return jTxtId;
    }

    public JTextField getjTxtNoTelepon() {
        return jTxtNoTelepon;
    }

    public void setjTxtNoTelepon(JTextField jTxtNoTelepon) {
        this.jTxtNoTelepon = jTxtNoTelepon;
    }

    public void setjTxtId(JTextField jTxtId) {
        this.jTxtId = jTxtId;
    }

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jBtnSignUpAnggota = new javax.swing.JButton();
        jTxtNamaSignUp = new javax.swing.JTextField();
        jTxtUsernameSignUp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtPasswordSignUp = new javax.swing.JTextField();
        jTxtAlamatSignUp = new javax.swing.JTextField();
        jTxtEmailSignUp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnSignUpPetugas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtNoTelepon = new javax.swing.JTextField();
        jBtnKembali = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");

        jBtnSignUpAnggota.setText("Signup Anggota");

        jTxtNamaSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNamaSignUpActionPerformed(evt);
            }
        });

        jTxtUsernameSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsernameSignUpActionPerformed(evt);
            }
        });

        jTxtPasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPasswordSignUpActionPerformed(evt);
            }
        });

        jTxtAlamatSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAlamatSignUpActionPerformed(evt);
            }
        });

        jTxtEmailSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailSignUpActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("Alamat");

        jLabel6.setText("Email");

        jBtnSignUpPetugas.setText("Signup Petugas");
        jBtnSignUpPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignUpPetugasActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        jTxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdActionPerformed(evt);
            }
        });

        jLabel8.setText("No Telepon");

        jBtnKembali.setText("Kembali");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jBtnSignUpAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSignUpPetugas)
                .addGap(29, 29, 29)
                .addComponent(jBtnKembali))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtUsernameSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNamaSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAlamatSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPasswordSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmailSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNoTelepon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNamaSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtUsernameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAlamatSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSignUpAnggota)
                    .addComponent(jBtnSignUpPetugas)
                    .addComponent(jBtnKembali))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUsernameSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsernameSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUsernameSignUpActionPerformed

    private void jTxtAlamatSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAlamatSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAlamatSignUpActionPerformed

    private void jTxtPasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPasswordSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPasswordSignUpActionPerformed

    private void jTxtEmailSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailSignUpActionPerformed

    private void jTxtNamaSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNamaSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNamaSignUpActionPerformed

    private void jBtnSignUpPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignUpPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSignUpPetugasActionPerformed

    private void jTxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SignUp().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnKembali;
    private javax.swing.JButton jBtnSignUpAnggota;
    private javax.swing.JButton jBtnSignUpPetugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtAlamatSignUp;
    private javax.swing.JTextField jTxtEmailSignUp;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNamaSignUp;
    private javax.swing.JTextField jTxtNoTelepon;
    private javax.swing.JTextField jTxtPasswordSignUp;
    private javax.swing.JTextField jTxtUsernameSignUp;
    // End of variables declaration//GEN-END:variables

    public void addListener(Controller aThis) {
        jBtnSignUpAnggota.addActionListener(aThis);
        jBtnSignUpPetugas.addActionListener(aThis);
        jBtnKembali.addActionListener(aThis);
    }
}
